version: '3.4'

name: yarp-with-service-discovery
services:
  consul:
    image: consul:1.15.4
    container_name: consul-dev-server
    command: ["consul", "agent", "-dev", "-client", "0.0.0.0", "-dns-port=8600", "-config-dir=/consul/config", "-log-level=debug"]
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"  # DNS port
      #- "389:389"
    networks:
      - dev_shared

  yarp:
    image: ${DOCKER_REGISTRY-}yarp
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "9090:8080"
      - "9091:8081"
    depends_on:
      - consul
    networks: 
        - dev_shared

  api1:
    image: ${DOCKER_REGISTRY-}api1
    build:
      context: .
      dockerfile: Samples/Api1/Dockerfile
    depends_on:
      - consul
    networks: 
        - dev_shared

  api2:
    image: ${DOCKER_REGISTRY-}api2
    build:
      context: .
      dockerfile: Samples/Api2/Dockerfile
    networks: 
        - dev_shared

networks:
  dev_shared:
    external: true