version: '3.4'

services:
  atiyanseir.b2b.apigateway:
    image: ${DOCKER_REGISTRY-}atiyanseirb2bapigateway
    container_name: dev-api-gateway

    networks:
      - dev-network      
    
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

networks:
  dev-network:
    name: dev-network
    external: true